### ISSUE TITLE
这个和rqalpha安装使用是一样的吗？

### ISSUE THREAD

**Issue by Cloud33** [DingTobest/Rqalpha-myquant-learning#2]
这个和rqalpha安装使用是一样的吗？
http://rqalpha.readthedocs.io/zh_CN/latest/intro/tutorial.html

**Comment by DingTobest** [comment]
把程序down下来就可以，有一些需要对应安装的包需要安装一下，比如bcolz，可能还会有一些其他的。和rqalpha基本是一样的，我这边增加了一个入口函数ats.main.py，从这个函数里面就可以执行策略和下载日线数据。里面的rqalpha除了我改的，和rqalpha一样，谢谢！

**Comment by DingTobest** [comment]
已解决，通过setup.py安装，与rqalpha一样
